# Generated by Django 6.0.6 on 2026-07-11 23:35

import Accounts.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=Accounts.storages.MediaStorage(), upload_to='profile_pictures/'),
        ),
    ]
