# Generated by Django 6.0.6 on 2026-07-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_reply_alter_comment_replies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='reply',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
