# Generated by Django 6.0.6 on 2026-07-11 23:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration of the episode in seconds'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='episode',
            name='file_size',
            field=models.PositiveBigIntegerField(help_text='Size of the audio file in bytes'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
