# Generated by Django 6.0.6 on 2026-07-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_alter_episode_duration_alter_episode_episode_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration of the episode in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='file_size',
            field=models.PositiveBigIntegerField(blank=True, help_text='Size of the audio file in bytes', null=True),
        ),
    ]
